spring:
  application:
    name: careerBuilderDev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:careerBuilderDev
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

